### ISSUE TITLE
Show module installation progress in CLI

### ISSUE THREAD

**Issue by depombo** [iasql/cli#14]
we'll need to figure out how to stream progress updates from the server to the client either by polling, writing parts of the `body` over time or something else

**Comment by dfellis** [comment]
Definitely would deprioritize this now, installation is on the order of 1-3 seconds now for all modules, so a progress bar is unnecessary.

**Comment by depombo** [comment]
> Definitely would deprioritize this now, installation is on the order of 1-3 seconds now for all modules, so a progress bar is unnecessary.

Agreed!

**Comment by depombo** [comment]
CLI is being deprecated so closing this out
